### ISSUE TITLE
Potential dependency conflicts between annotell-input-api and requests

### ISSUE THREAD

**Issue by NeolithEra** [annotell/annotell-python#4]
Hi, as shown in the following full dependency graph of  **_annotell-input-api_**, **_annotell-input-api_** requires _**requests**_ (>=2.23.0)， while the installed version of **_annotell-auth _**(1.4.0) requires _**requests>=2.20,<3**_.

According to Pip's “first found wins” installation strategy, _**requests 2.23.0**_ is the actually installed version.  

Although the first found package version _**requests 2.23.0**_ just satisfies the later dependency constraint （_**requests>=2.20,<3**_), it will lead to a build failure once developers release a newer version of requests.

### Dependency tree--------
```
annotell-input-api - 0.2.3 
| +- annotell-auth(install version:1.4.0 version range:>=1.3.0)
| | +- authlib(install version:0.14.3 version range:>=0.14.1,<1)
| | +- requests(install version:2.23.0 version range:>=2.20,<3)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- annotell-cloud-storage(install version:0.4.0 version range:>=0.3.0)
| | +- google-cloud-storage(install version:1.28.1 version range:>=1.23.0,<2)
| | +- requests(install version:2.23.0 version range:>2.20<3)
| | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- click(install version:7.1.1 version range:>=7.1.1)
| +- Pillow(install version:7.1.1 version range:>=7.0.0)
| +- requests(install version:2.23.0 version range:>=2.23.0)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- tabulate(install version:0.8.7 version range:>=0.8.7) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_requests_** to be **_<=3_**.
2.	Remove your direct dependency **_requests_**, and use the **_requests_** transitively introduced by **_annotell-auth _**.
3.	Ask your direct dependency annotell-auth to loosen the version range of **_requests_** to be **_>=2.0.1_**.
@langkilde Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by NeolithEra** [comment]
@langkilde,Could you help me review this issue? Thx :p

**Comment by MichelEdkrantz** [comment]
Not an issue with the dependency resolver in recent pip versions
